# Generated by Django 4.2 on 2023-04-20 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_like_value_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
